# Generated by Django 4.2.6 on 2023-11-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_genre_mood_alter_song_genre_alter_song_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
