# Generated by Django 4.2.6 on 2023-11-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='artist',
            new_name='uploader',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='uploader',
        ),
    ]
