# Generated by Django 4.2.6 on 2023-11-25 15:51

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_song_lyrics_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics_json',
            field=models.JSONField(blank=True, default=music.models.default_lyrics, null=True),
        ),
    ]
