# Generated by Django 4.2.6 on 2023-11-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_playlist_description_alter_playlist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='artist',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='music.artist'),
        ),
    ]
