# Generated by Django 4.2.6 on 2023-11-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_favourite_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='lyrics_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
