# Generated by Django 4.2.6 on 2023-11-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_playlist_lyrics_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='lyrics_url',
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
