# Generated by Django 4.2.6 on 2023-11-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_playlist_lyrics_url_song_lyrics_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
