# Generated by Django 4.2.6 on 2023-11-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_artist_thumbnail_url_alter_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
