version: '3'

services:
  soundly-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soundly-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app