# Generated by Django 4.2.6 on 2023-10-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_is_valid_delete_activetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
