# Generated by Django 4.2.6 on 2023-11-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='audio_1',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='audio_2',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
