# Generated by Django 4.2.6 on 2023-11-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_audio_1_alter_game_audio_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='audio_2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='option3',
        ),
    ]
