# Generated by Django 4.2.6 on 2023-11-26 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_game_option3_game_option4"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Score",
        ),
    ]
